/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package artistdistance.schema;
@org.apache.avro.specific.AvroGenerated
public enum BfsStatus implements org.apache.avro.generic.GenericEnumSymbol<BfsStatus> {
  unvisited, frontier, visited  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BfsStatus\",\"namespace\":\"artistdistance.schema\",\"symbols\":[\"unvisited\",\"frontier\",\"visited\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
