/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package artistdistance.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BfsVertex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5992987524469291094L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BfsVertex\",\"namespace\":\"artistdistance.schema\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"neighbors\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]},{\"name\":\"degree\",\"type\":\"int\",\"default\":0},{\"name\":\"distance\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"parent\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"BfsStatus\",\"symbols\":[\"unvisited\",\"frontier\",\"visited\"]},\"default\":\"unvisited\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BfsVertex> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BfsVertex> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BfsVertex> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BfsVertex> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BfsVertex> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BfsVertex to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BfsVertex from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BfsVertex instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BfsVertex fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.util.List<java.lang.String> neighbors;
  private int degree;
  private java.lang.Integer distance;
  private java.lang.String parent;
  private artistdistance.schema.BfsStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BfsVertex() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param neighbors The new value for neighbors
   * @param degree The new value for degree
   * @param distance The new value for distance
   * @param parent The new value for parent
   * @param status The new value for status
   */
  public BfsVertex(java.lang.String id, java.util.List<java.lang.String> neighbors, java.lang.Integer degree, java.lang.Integer distance, java.lang.String parent, artistdistance.schema.BfsStatus status) {
    this.id = id;
    this.neighbors = neighbors;
    this.degree = degree;
    this.distance = distance;
    this.parent = parent;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return neighbors;
    case 2: return degree;
    case 3: return distance;
    case 4: return parent;
    case 5: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: neighbors = (java.util.List<java.lang.String>)value$; break;
    case 2: degree = (java.lang.Integer)value$; break;
    case 3: distance = (java.lang.Integer)value$; break;
    case 4: parent = value$ != null ? value$.toString() : null; break;
    case 5: status = (artistdistance.schema.BfsStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'neighbors' field.
   * @return The value of the 'neighbors' field.
   */
  public java.util.List<java.lang.String> getNeighbors() {
    return neighbors;
  }


  /**
   * Sets the value of the 'neighbors' field.
   * @param value the value to set.
   */
  public void setNeighbors(java.util.List<java.lang.String> value) {
    this.neighbors = value;
  }

  /**
   * Gets the value of the 'degree' field.
   * @return The value of the 'degree' field.
   */
  public int getDegree() {
    return degree;
  }


  /**
   * Sets the value of the 'degree' field.
   * @param value the value to set.
   */
  public void setDegree(int value) {
    this.degree = value;
  }

  /**
   * Gets the value of the 'distance' field.
   * @return The value of the 'distance' field.
   */
  public java.lang.Integer getDistance() {
    return distance;
  }


  /**
   * Sets the value of the 'distance' field.
   * @param value the value to set.
   */
  public void setDistance(java.lang.Integer value) {
    this.distance = value;
  }

  /**
   * Gets the value of the 'parent' field.
   * @return The value of the 'parent' field.
   */
  public java.lang.String getParent() {
    return parent;
  }


  /**
   * Sets the value of the 'parent' field.
   * @param value the value to set.
   */
  public void setParent(java.lang.String value) {
    this.parent = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public artistdistance.schema.BfsStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(artistdistance.schema.BfsStatus value) {
    this.status = value;
  }

  /**
   * Creates a new BfsVertex RecordBuilder.
   * @return A new BfsVertex RecordBuilder
   */
  public static artistdistance.schema.BfsVertex.Builder newBuilder() {
    return new artistdistance.schema.BfsVertex.Builder();
  }

  /**
   * Creates a new BfsVertex RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BfsVertex RecordBuilder
   */
  public static artistdistance.schema.BfsVertex.Builder newBuilder(artistdistance.schema.BfsVertex.Builder other) {
    if (other == null) {
      return new artistdistance.schema.BfsVertex.Builder();
    } else {
      return new artistdistance.schema.BfsVertex.Builder(other);
    }
  }

  /**
   * Creates a new BfsVertex RecordBuilder by copying an existing BfsVertex instance.
   * @param other The existing instance to copy.
   * @return A new BfsVertex RecordBuilder
   */
  public static artistdistance.schema.BfsVertex.Builder newBuilder(artistdistance.schema.BfsVertex other) {
    if (other == null) {
      return new artistdistance.schema.BfsVertex.Builder();
    } else {
      return new artistdistance.schema.BfsVertex.Builder(other);
    }
  }

  /**
   * RecordBuilder for BfsVertex instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BfsVertex>
    implements org.apache.avro.data.RecordBuilder<BfsVertex> {

    private java.lang.String id;
    private java.util.List<java.lang.String> neighbors;
    private int degree;
    private java.lang.Integer distance;
    private java.lang.String parent;
    private artistdistance.schema.BfsStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(artistdistance.schema.BfsVertex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.neighbors)) {
        this.neighbors = data().deepCopy(fields()[1].schema(), other.neighbors);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.degree)) {
        this.degree = data().deepCopy(fields()[2].schema(), other.degree);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.distance)) {
        this.distance = data().deepCopy(fields()[3].schema(), other.distance);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.parent)) {
        this.parent = data().deepCopy(fields()[4].schema(), other.parent);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing BfsVertex instance
     * @param other The existing instance to copy.
     */
    private Builder(artistdistance.schema.BfsVertex other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.neighbors)) {
        this.neighbors = data().deepCopy(fields()[1].schema(), other.neighbors);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.degree)) {
        this.degree = data().deepCopy(fields()[2].schema(), other.degree);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.distance)) {
        this.distance = data().deepCopy(fields()[3].schema(), other.distance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.parent)) {
        this.parent = data().deepCopy(fields()[4].schema(), other.parent);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'neighbors' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getNeighbors() {
      return neighbors;
    }


    /**
      * Sets the value of the 'neighbors' field.
      * @param value The value of 'neighbors'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setNeighbors(java.util.List<java.lang.String> value) {
      validate(fields()[1], value);
      this.neighbors = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'neighbors' field has been set.
      * @return True if the 'neighbors' field has been set, false otherwise.
      */
    public boolean hasNeighbors() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'neighbors' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearNeighbors() {
      neighbors = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'degree' field.
      * @return The value.
      */
    public int getDegree() {
      return degree;
    }


    /**
      * Sets the value of the 'degree' field.
      * @param value The value of 'degree'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setDegree(int value) {
      validate(fields()[2], value);
      this.degree = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'degree' field has been set.
      * @return True if the 'degree' field has been set, false otherwise.
      */
    public boolean hasDegree() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'degree' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearDegree() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'distance' field.
      * @return The value.
      */
    public java.lang.Integer getDistance() {
      return distance;
    }


    /**
      * Sets the value of the 'distance' field.
      * @param value The value of 'distance'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setDistance(java.lang.Integer value) {
      validate(fields()[3], value);
      this.distance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'distance' field has been set.
      * @return True if the 'distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'distance' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearDistance() {
      distance = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'parent' field.
      * @return The value.
      */
    public java.lang.String getParent() {
      return parent;
    }


    /**
      * Sets the value of the 'parent' field.
      * @param value The value of 'parent'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setParent(java.lang.String value) {
      validate(fields()[4], value);
      this.parent = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'parent' field has been set.
      * @return True if the 'parent' field has been set, false otherwise.
      */
    public boolean hasParent() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'parent' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearParent() {
      parent = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public artistdistance.schema.BfsStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder setStatus(artistdistance.schema.BfsStatus value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public artistdistance.schema.BfsVertex.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BfsVertex build() {
      try {
        BfsVertex record = new BfsVertex();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.neighbors = fieldSetFlags()[1] ? this.neighbors : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
        record.degree = fieldSetFlags()[2] ? this.degree : (java.lang.Integer) defaultValue(fields()[2]);
        record.distance = fieldSetFlags()[3] ? this.distance : (java.lang.Integer) defaultValue(fields()[3]);
        record.parent = fieldSetFlags()[4] ? this.parent : (java.lang.String) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (artistdistance.schema.BfsStatus) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BfsVertex>
    WRITER$ = (org.apache.avro.io.DatumWriter<BfsVertex>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BfsVertex>
    READER$ = (org.apache.avro.io.DatumReader<BfsVertex>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    long size0 = this.neighbors.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.neighbors) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeInt(this.degree);

    if (this.distance == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.distance);
    }

    if (this.parent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.parent);
    }

    out.writeEnum(this.status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.neighbors;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("neighbors").schema());
        this.neighbors = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

      this.degree = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.distance = null;
      } else {
        this.distance = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.parent = null;
      } else {
        this.parent = in.readString();
      }

      this.status = artistdistance.schema.BfsStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.neighbors;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("neighbors").schema());
            this.neighbors = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        case 2:
          this.degree = in.readInt();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.distance = null;
          } else {
            this.distance = in.readInt();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.parent = null;
          } else {
            this.parent = in.readString();
          }
          break;

        case 5:
          this.status = artistdistance.schema.BfsStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (neighbors == null ? 0 : neighbors.hashCode());
    result = 31 * result + Integer.hashCode(degree);
    result = 31 * result + (distance == null ? 0 : distance.hashCode());
    result = 31 * result + (parent == null ? 0 : parent.hashCode());
    result = 31 * result + (status == null ? 0 : ((java.lang.Enum) status).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BfsVertex)) {
      return false;
    }
    BfsVertex other = (BfsVertex) o;
    if (!java.util.Objects.equals(this.id, other.id)) {
      return false;
    }
    if (!java.util.Objects.equals(this.neighbors, other.neighbors)) {
      return false;
    }
    if (this.degree != other.degree) {
      return false;
    }
    if (!java.util.Objects.equals(this.distance, other.distance)) {
      return false;
    }
    if (!java.util.Objects.equals(this.parent, other.parent)) {
      return false;
    }
    if (!java.util.Objects.equals(this.status, other.status)) {
      return false;
    }
    return true;
  }
}










