"storage": {
  dfs: {
    type: "file",
    connection: "file:///",
    workspaces: {
      msd: {
        location: ${DRILL_DATA_DIR},
        writable: false,
        defaultInputFormat: "parquet",
        allowAccessOutsideWorkspace: false
      }
    },
    formats: {
      parquet: {
        type: "parquet"
      }
    },
    enabled: true
  }
}
